### ISSUE TITLE
请问换成glm4-chat的int量化模型可以吗

### ISSUE THREAD

**Issue by moonlight123154** [CadenCao/vllm-qwen1.5-StreamChat#2]
但是会报错
Traceback (most recent call last):
  File "/home/workspace/workspace_csh/vllm_test2.py", line 189, in <module>
    generation_config, tokenizer, stop_tokens, engine = model_load_vllm(args.model_path,
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/workspace_csh/vllm_test2.py", line 28, in model_load_vllm
    stop_tokens = [tokenizer.convert_tokens_to_ids('<|im_start|>'),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs_gpu/miniconda3/envs/glm3/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 645, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs_gpu/miniconda3/envs/glm3/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 658, in _convert_token_to_id_with_added_voc
    return self._convert_token_to_id(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat-GPTQ-Int8/tokenization_chatglm.py", line 95, in _convert_token_to_id
    return self.mergeable_ranks[token]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: '<|im_start|>'

**Comment by CadenCao** [comment]
量化模型好像是不行的
